version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    volumes:
      - .:/var/www
    tty: true

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage/docker/logs/nginx:/var/log/nginx/
      - ./:/var/www
    depends_on:
      - app
      - mysql